version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: noserverconvert
    volumes:
      - ./dist:/usr/share/nginx/html
    dns:
      - 1.1.1.1
    restart: unless-stopped
    networks:
      proxy:
    labels:
      # Basis-Konfiguration
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      
      # Router Konfiguration
      - "traefik.http.routers.noserverconvert.entrypoints=websecure"
      - "traefik.http.routers.noserverconvert.rule=Host(`convert.fr4iser.com`)"
      - "traefik.http.routers.noserverconvert.tls=true"
      - "traefik.http.routers.noserverconvert.tls.certresolver=http_resolver"
      
      # Middleware Chain
      - "traefik.http.routers.noserverconvert.middlewares=default@file,rate-limit@docker"
      
      # Service Konfiguration
      - "traefik.http.services.noserverconvert.loadbalancer.server.port=80"
      
      # Sticky Sessions
      - "traefik.http.services.noserverconvert.loadbalancer.sticky.cookie.httpOnly=true"
      - "traefik.http.services.noserverconvert.loadbalancer.sticky.cookie.secure=true"

networks:
  proxy:
    external: true
