version: '3.8'

services:
  noserverconvert-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: noserverconvert
    ports:
      - "8080:80"
    dns:
      - 1.1.1.1
    restart: unless-stopped

    # Traefik labels - commented out for git
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.docker.network=proxy"
    #   - "traefik.http.routers.noserverconvert.entrypoints=websecure"
    #   - "traefik.http.routers.noserverconvert.rule=Host(`your-domain.com`)"
    #   - "traefik.http.routers.noserverconvert.tls=true"
    #   - "traefik.http.routers.noserverconvert.tls.certresolver=http_resolver"
    #   - "traefik.http.routers.noserverconvert.middlewares=default@file,rate-limit@docker"
    #   - "traefik.http.services.noserverconvert.loadbalancer.server.port=80"
    #   - "traefik.http.services.noserverconvert.loadbalancer.sticky.cookie.httpOnly=true"
    #   - "traefik.http.services.noserverconvert.loadbalancer.sticky.cookie.secure=true"

# networks:
#   proxy:
#     external: true
