version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: noserverconvert
    volumes:
      - ./dist:/usr/share/nginx/html
    dns:
      - 1.1.1.1
    restart: unless-stopped
    ports:
      - 8080:80